apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-chinachu
spec:
  storageClassName: chinachu
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.10.220
    path: "/mnt/pool/chinachu"
